--------------------------------------------------------
--  Arquivo criado - sexta-feira-novembro-23-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SQ_ALIMENTACAO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_ALIMENTACAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ATIVIDADE_FISICA
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_ATIVIDADE_FISICA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CONTATO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_CONTATO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_EMAIL
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_EMAIL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ENDERECO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_ENDERECO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ESTADO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_ESTADO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 28 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_EVOLUCAO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_EVOLUCAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_MEDIDAS_CORPORAIS
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_MEDIDAS_CORPORAIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_MENU
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_MENU"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PAIS
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_PAIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 60 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PESO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_PESO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 33 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PLANEJAMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_PLANEJAMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PRESSAO_ARTERIAL
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_PRESSAO_ARTERIAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_TELEFONE
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_TELEFONE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_TIPO_ALIMENTACAO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_TIPO_ALIMENTACAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_TIPO_ATIVIDADE_FISICA
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_TIPO_ATIVIDADE_FISICA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_TIPO_EMAIL
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_TIPO_EMAIL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_TIPO_ENDERECO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_TIPO_ENDERECO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_TIPO_TELEFONE
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_TIPO_TELEFONE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SQ_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table T_HT_ALIMENTACAO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_ALIMENTACAO" 
   (	"CD_ALIMENTACAO" NUMBER(9,0), 
	"CD_USUARIO" NUMBER(9,0), 
	"NM_ALIMENTO" VARCHAR2(150 BYTE), 
	"DS_ALIMENTO" VARCHAR2(250 BYTE), 
	"VL_CALORIAS" NUMBER(6,3), 
	"DT_CONSUMO" DATE, 
	"CD_TIPO_ALIMENTACAO" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_ATIVIDADE_FISICA
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_ATIVIDADE_FISICA" 
   (	"CD_ATIVIDADE_FISICA" NUMBER(9,0), 
	"NM_ATIVIDADE_FISICA" VARCHAR2(200 BYTE), 
	"DS_ATIVIDADE_FISICA" VARCHAR2(250 BYTE), 
	"VL_GASTO_CALORICO" FLOAT(126), 
	"DT_REALIZADA" DATE, 
	"CD_TIPO_ATIVIDADE_FISICA" NUMBER(3,0), 
	"CD_USUARIO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_CONTATO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_CONTATO" 
   (	"CD_CONTATO" NUMBER(9,0), 
	"CD_USUARIO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_CONTATO_EMAIL
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_CONTATO_EMAIL" 
   (	"CD_CONTATO" NUMBER(9,0), 
	"CD_EMAIL" NUMBER(3,0), 
	"CD_USUARIO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_CONTATO_TELEFONE
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_CONTATO_TELEFONE" 
   (	"CD_CONTATO" NUMBER(9,0), 
	"CD_TELEFONE" NUMBER(9,0), 
	"CD_USUARIO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_EMAIL
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_EMAIL" 
   (	"CD_EMAIL" NUMBER(3,0), 
	"DS_EMAIL" VARCHAR2(200 BYTE), 
	"CD_TIPO_EMAIL" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_ENDERECO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_ENDERECO" 
   (	"CD_ENDERECO" NUMBER(6,0), 
	"CD_TIPO_ENDERECO" NUMBER(3,0), 
	"CD_ESTADO" NUMBER(3,0), 
	"DS_RUA" VARCHAR2(150 BYTE), 
	"VL_NUMERO" VARCHAR2(20 BYTE), 
	"DS_CAIXA_POSTAL" VARCHAR2(30 BYTE), 
	"DS_BAIRRO" VARCHAR2(50 BYTE), 
	"DS_CIDADE" VARCHAR2(200 BYTE), 
	"VL_CEP" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_ENDERECO_USUARIO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_ENDERECO_USUARIO" 
   (	"CD_ENDERECO" NUMBER(6,0), 
	"CD_USUARIO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_ESTADO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_ESTADO" 
   (	"CD_ESTADO" NUMBER(3,0), 
	"CD_PAIS" NUMBER(4,0), 
	"NM_ESTADO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_EVOLUCAO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_EVOLUCAO" 
   (	"CD_EVOLUCAO" NUMBER(9,0), 
	"CD_PLANEJAMENTO" NUMBER(6,0), 
	"CD_PESO" NUMBER(9,0), 
	"CD_MEDIDAS" NUMBER(9,0), 
	"CD_PRESSAO" NUMBER(9,0), 
	"DS_FOTO" VARCHAR2(250 BYTE), 
	"DT_REGISTRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_HISTORICO_ACESSO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_HISTORICO_ACESSO" 
   (	"CD_USUARIO" NUMBER(9,0), 
	"DT_ACESSO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_MEDIDAS_CORPORAIS
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_MEDIDAS_CORPORAIS" 
   (	"CD_MEDIDAS" NUMBER(9,0), 
	"CD_USUARIO" NUMBER(9,0), 
	"VL_PEITO" NUMBER(4,3), 
	"VL_CINTURA" NUMBER(4,3), 
	"VL_QUADRIL" NUMBER(4,3), 
	"VL_PANTURRILHA" NUMBER(4,3), 
	"VL_PESCOCO" NUMBER(4,3), 
	"VL_LARGURA_OMBROS" NUMBER(4,3), 
	"VL_COMPRIMENTO_BRACO" NUMBER(4,3), 
	"VL_PULSO" NUMBER(4,3), 
	"DT_MEDICAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_MENU
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_MENU" 
   (	"CD_MENU" NUMBER(3,0), 
	"NM_MENU" VARCHAR2(100 BYTE), 
	"DS_CAMINHO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_PAIS
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_PAIS" 
   (	"CD_PAIS" NUMBER(4,0), 
	"NM_PAIS" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_PESO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_PESO" 
   (	"CD_PESO" NUMBER(9,0), 
	"VL_PESO" FLOAT(126), 
	"DT_MEDICAO" DATE, 
	"CD_USUARIO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_PLANEJAMENTO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_PLANEJAMENTO" 
   (	"CD_PLANEJAMENTO" NUMBER(6,0), 
	"CD_USUARIO" NUMBER(9,0), 
	"NM_PLANO" VARCHAR2(150 BYTE), 
	"DS_OBJETIVO" VARCHAR2(255 BYTE), 
	"DT_INICIO" DATE, 
	"DT_FIM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_PRESSAO_ARTERIAL
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_PRESSAO_ARTERIAL" 
   (	"CD_PRESSAO" NUMBER(9,0), 
	"CD_USUARIO" NUMBER(9,0), 
	"VL_PRESSAO_SISTOLICA" FLOAT(126), 
	"VL_PRESSAO_DIASTOLICA" FLOAT(126), 
	"DT_MEDICAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_RELEMBRAR_SENHA
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_RELEMBRAR_SENHA" 
   (	"CD_USUARIO" NUMBER(9,0), 
	"DM_EMAIL" VARCHAR2(250 BYTE), 
	"DT_ENVIO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_TELEFONE
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_TELEFONE" 
   (	"CD_TELEFONE" NUMBER(9,0), 
	"CD_TIPO_TELEFONE" NUMBER(3,0), 
	"VL_DDI" VARCHAR2(3 BYTE), 
	"VL_DDD" VARCHAR2(3 BYTE), 
	"VL_PREFIXO" VARCHAR2(5 BYTE), 
	"VL_SUFIXO" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_TIPO_ALIMENTACAO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_TIPO_ALIMENTACAO" 
   (	"CD_TIPO_ALIMENTACAO" NUMBER(3,0), 
	"NM_TIPO_ALIMENTACAO" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_TIPO_ATIVIDADE_FISICA
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_TIPO_ATIVIDADE_FISICA" 
   (	"CD_TIPO_ATIVIDADE_FISICA" NUMBER(3,0), 
	"NM_TIPO_ATIVIDADE_FISICA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_TIPO_EMAIL
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_TIPO_EMAIL" 
   (	"CD_TIPO_EMAIL" NUMBER(3,0), 
	"NM_TIPO_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_TIPO_ENDERECO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_TIPO_ENDERECO" 
   (	"CD_TIPO_ENDERECO" NUMBER(3,0), 
	"NM_TIPO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_TIPO_TELEFONE
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_TIPO_TELEFONE" 
   (	"CD_TIPO_TELEFONE" NUMBER(3,0), 
	"NM_TIPO_TELEFONE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table T_HT_USUARIO
--------------------------------------------------------

  CREATE TABLE "XE"."T_HT_USUARIO" 
   (	"CD_USUARIO" NUMBER(9,0), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"SENHA" VARCHAR2(20 BYTE), 
	"NM_NOME" VARCHAR2(100 BYTE), 
	"NM_SOBRENOME" VARCHAR2(100 BYTE), 
	"SEXO" VARCHAR2(1 BYTE), 
	"DT_NASCIMENTO" DATE, 
	"VL_ALTURA" NUMBER(3,2), 
	"DS_FOTO" VARCHAR2(255 BYTE), 
	"DT_CADASTRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into XE.T_HT_ALIMENTACAO
SET DEFINE OFF;
Insert into XE.T_HT_ALIMENTACAO (CD_ALIMENTACAO,CD_USUARIO,NM_ALIMENTO,DS_ALIMENTO,VL_CALORIAS,DT_CONSUMO,CD_TIPO_ALIMENTACAO) values ('7','2','macarrão','prato principal','500',to_date('22/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_ALIMENTACAO (CD_ALIMENTACAO,CD_USUARIO,NM_ALIMENTO,DS_ALIMENTO,VL_CALORIAS,DT_CONSUMO,CD_TIPO_ALIMENTACAO) values ('8','2','Ovos mexidos','desjejum','800',to_date('22/11/18','DD/MM/RR'),'1');
Insert into XE.T_HT_ALIMENTACAO (CD_ALIMENTACAO,CD_USUARIO,NM_ALIMENTO,DS_ALIMENTO,VL_CALORIAS,DT_CONSUMO,CD_TIPO_ALIMENTACAO) values ('9','2','macarrão','prato principal','500',to_date('22/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_ALIMENTACAO (CD_ALIMENTACAO,CD_USUARIO,NM_ALIMENTO,DS_ALIMENTO,VL_CALORIAS,DT_CONSUMO,CD_TIPO_ALIMENTACAO) values ('10','2','Ovos mexidos','desjejum','800',to_date('22/11/18','DD/MM/RR'),'1');
REM INSERTING into XE.T_HT_ATIVIDADE_FISICA
SET DEFINE OFF;
Insert into XE.T_HT_ATIVIDADE_FISICA (CD_ATIVIDADE_FISICA,NM_ATIVIDADE_FISICA,DS_ATIVIDADE_FISICA,VL_GASTO_CALORICO,DT_REALIZADA,CD_TIPO_ATIVIDADE_FISICA,CD_USUARIO) values ('1','Corrida','Voltas no parque','500,5',to_date('22/11/18','DD/MM/RR'),'3','2');
Insert into XE.T_HT_ATIVIDADE_FISICA (CD_ATIVIDADE_FISICA,NM_ATIVIDADE_FISICA,DS_ATIVIDADE_FISICA,VL_GASTO_CALORICO,DT_REALIZADA,CD_TIPO_ATIVIDADE_FISICA,CD_USUARIO) values ('2','Natação','100 metros','456,5',to_date('22/11/18','DD/MM/RR'),'2','2');
Insert into XE.T_HT_ATIVIDADE_FISICA (CD_ATIVIDADE_FISICA,NM_ATIVIDADE_FISICA,DS_ATIVIDADE_FISICA,VL_GASTO_CALORICO,DT_REALIZADA,CD_TIPO_ATIVIDADE_FISICA,CD_USUARIO) values ('3','Xadrez','duas partidas','300',to_date('22/11/18','DD/MM/RR'),'1','2');
REM INSERTING into XE.T_HT_CONTATO
SET DEFINE OFF;
REM INSERTING into XE.T_HT_CONTATO_EMAIL
SET DEFINE OFF;
REM INSERTING into XE.T_HT_CONTATO_TELEFONE
SET DEFINE OFF;
REM INSERTING into XE.T_HT_EMAIL
SET DEFINE OFF;
REM INSERTING into XE.T_HT_ENDERECO
SET DEFINE OFF;
REM INSERTING into XE.T_HT_ENDERECO_USUARIO
SET DEFINE OFF;
REM INSERTING into XE.T_HT_ESTADO
SET DEFINE OFF;
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('1','45','ACRE');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('2','45','ALAGOAS');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('3','45','AMAPA');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('4','45','AMAZONAS');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('5','45','BAHIA');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('6','45','CEARA');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('7','45','DISTRITO FEDERAL');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('8','45','ESPIRITO SANTO');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('9','45','GOIAS');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('10','45','MARANHAO');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('11','45','MATO GROSSO');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('12','45','MATO GROSSO DO SUL');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('13','45','MINAS GERAIS');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('14','45','PARA');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('15','45','PARAIBA');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('16','45','PARANA');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('17','45','PERNAMBUCO');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('18','45','PIAUI');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('19','45','RIO DE JANEIRO');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('20','45','RIO GRANDE DO NORTE');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('21','45','RIO GRANDE DO SUL');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('22','45','RONDONIA');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('23','45','RORAIMA');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('24','45','SANTA CATARINA');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('25','45','SAO PAULO');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('26','45','SERGIPE');
Insert into XE.T_HT_ESTADO (CD_ESTADO,CD_PAIS,NM_ESTADO) values ('27','45','TOCANTINS');
REM INSERTING into XE.T_HT_EVOLUCAO
SET DEFINE OFF;
REM INSERTING into XE.T_HT_HISTORICO_ACESSO
SET DEFINE OFF;
REM INSERTING into XE.T_HT_MEDIDAS_CORPORAIS
SET DEFINE OFF;
REM INSERTING into XE.T_HT_MENU
SET DEFINE OFF;
REM INSERTING into XE.T_HT_PAIS
SET DEFINE OFF;
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('1','ABISSINIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('2','ACORES');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('3','AFAR FRANCES');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('4','AFEGANISTAO');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('5','ALBANIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('6','ALEMANHA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('7','ALTO VOLTA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('8','ANDORA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('9','ANGOLA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('10','ANTARTICA FRANCESA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('11','ANTARTICO ARGENTINO');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('12','ANTARTICO BRITANICO TERRITORIO');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('13','ANTARTICO CHILENO');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('14','ANTARTICO NORUEGUES');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('15','ANTIGUA E DEP BARBUDA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('16','ANTILHAS HOLANDESAS');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('17','APATRIDA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('18','ARABIA SAUDITA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('19','ARGELIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('20','ARGENTINA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('21','ARMENIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('22','ARQUIPELAGO DE BISMARK');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('23','ARQUIPELAGO MANAHIKI');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('24','ARQUIPELAGO MIDWAY');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('25','ARUBA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('26','ASCENCAO E TRISTAO DA CUNHAIS');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('27','ASHMORE E CARTIER');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('28','AUSTRALIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('29','AUSTRIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('30','AZERBAIJAO');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('31','BAHRAIN');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('32','BANGLADESH');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('33','BARBADOS');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('34','BASHKISTA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('35','BECHUANA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('36','BELGICA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('37','BELIZE');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('38','BENIN');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('39','BERMUDAS');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('40','BHUTAN');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('41','BIRMANIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('42','BOLIVIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('43','BOSNIA HERZEGOVINA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('44','BOTSWANA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('45','BRASIL');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('46','BRUNEI');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('47','BURUNDI');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('48','BURYAT');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('49','CABO VERDE');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('50','CAMAROES');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('51','CANADA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('52','CARELIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('53','CASAQUISTAO');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('54','CHINA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('55','CHINA TAIWAN');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('56','CHIPRE');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('57','CHUVASH');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('58','COLOMBIA');
Insert into XE.T_HT_PAIS (CD_PAIS,NM_PAIS) values ('59','COMUNIDADE DAS BAHAMAS');
REM INSERTING into XE.T_HT_PESO
SET DEFINE OFF;
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('21','85,6',to_date('22/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('22','92,5',to_date('22/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('23','69,5',to_date('22/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('24','98,5',to_date('22/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('25','75,5',to_date('22/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('26','46',to_date('23/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('27','46',to_date('23/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('28','67,9',to_date('23/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('29','67,98',to_date('23/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('30','68,45',to_date('23/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('31','67,78',to_date('23/11/18','DD/MM/RR'),'2');
Insert into XE.T_HT_PESO (CD_PESO,VL_PESO,DT_MEDICAO,CD_USUARIO) values ('32','34,78',to_date('23/11/18','DD/MM/RR'),'2');
REM INSERTING into XE.T_HT_PLANEJAMENTO
SET DEFINE OFF;
REM INSERTING into XE.T_HT_PRESSAO_ARTERIAL
SET DEFINE OFF;
Insert into XE.T_HT_PRESSAO_ARTERIAL (CD_PRESSAO,CD_USUARIO,VL_PRESSAO_SISTOLICA,VL_PRESSAO_DIASTOLICA,DT_MEDICAO) values ('26','2','8,7','13,2',to_date('22/11/18','DD/MM/RR'));
Insert into XE.T_HT_PRESSAO_ARTERIAL (CD_PRESSAO,CD_USUARIO,VL_PRESSAO_SISTOLICA,VL_PRESSAO_DIASTOLICA,DT_MEDICAO) values ('27','2','9,7','15,2',to_date('22/11/18','DD/MM/RR'));
Insert into XE.T_HT_PRESSAO_ARTERIAL (CD_PRESSAO,CD_USUARIO,VL_PRESSAO_SISTOLICA,VL_PRESSAO_DIASTOLICA,DT_MEDICAO) values ('28','2','10,7','12,2',to_date('22/11/18','DD/MM/RR'));
Insert into XE.T_HT_PRESSAO_ARTERIAL (CD_PRESSAO,CD_USUARIO,VL_PRESSAO_SISTOLICA,VL_PRESSAO_DIASTOLICA,DT_MEDICAO) values ('29','2','10,7','12,2',to_date('22/11/18','DD/MM/RR'));
Insert into XE.T_HT_PRESSAO_ARTERIAL (CD_PRESSAO,CD_USUARIO,VL_PRESSAO_SISTOLICA,VL_PRESSAO_DIASTOLICA,DT_MEDICAO) values ('30','2','10,7','12,2',to_date('22/11/18','DD/MM/RR'));
REM INSERTING into XE.T_HT_RELEMBRAR_SENHA
SET DEFINE OFF;
REM INSERTING into XE.T_HT_TELEFONE
SET DEFINE OFF;
REM INSERTING into XE.T_HT_TIPO_ALIMENTACAO
SET DEFINE OFF;
Insert into XE.T_HT_TIPO_ALIMENTACAO (CD_TIPO_ALIMENTACAO,NM_TIPO_ALIMENTACAO) values ('1','CAFÉ');
Insert into XE.T_HT_TIPO_ALIMENTACAO (CD_TIPO_ALIMENTACAO,NM_TIPO_ALIMENTACAO) values ('2','ALMOÇO');
Insert into XE.T_HT_TIPO_ALIMENTACAO (CD_TIPO_ALIMENTACAO,NM_TIPO_ALIMENTACAO) values ('3','JANTAR');
Insert into XE.T_HT_TIPO_ALIMENTACAO (CD_TIPO_ALIMENTACAO,NM_TIPO_ALIMENTACAO) values ('4','LANCHE');
REM INSERTING into XE.T_HT_TIPO_ATIVIDADE_FISICA
SET DEFINE OFF;
Insert into XE.T_HT_TIPO_ATIVIDADE_FISICA (CD_TIPO_ATIVIDADE_FISICA,NM_TIPO_ATIVIDADE_FISICA) values ('1','BAIXA INTENSIDADE');
Insert into XE.T_HT_TIPO_ATIVIDADE_FISICA (CD_TIPO_ATIVIDADE_FISICA,NM_TIPO_ATIVIDADE_FISICA) values ('2','INTENSIDADE MODERADA');
Insert into XE.T_HT_TIPO_ATIVIDADE_FISICA (CD_TIPO_ATIVIDADE_FISICA,NM_TIPO_ATIVIDADE_FISICA) values ('3','ALTA INTENSIDADE');
REM INSERTING into XE.T_HT_TIPO_EMAIL
SET DEFINE OFF;
Insert into XE.T_HT_TIPO_EMAIL (CD_TIPO_EMAIL,NM_TIPO_EMAIL) values ('1','PESSOAL');
Insert into XE.T_HT_TIPO_EMAIL (CD_TIPO_EMAIL,NM_TIPO_EMAIL) values ('2','COMERCIAL');
Insert into XE.T_HT_TIPO_EMAIL (CD_TIPO_EMAIL,NM_TIPO_EMAIL) values ('3','GRUPO');
REM INSERTING into XE.T_HT_TIPO_ENDERECO
SET DEFINE OFF;
Insert into XE.T_HT_TIPO_ENDERECO (CD_TIPO_ENDERECO,NM_TIPO) values ('1','RESIDÊNCIAL');
Insert into XE.T_HT_TIPO_ENDERECO (CD_TIPO_ENDERECO,NM_TIPO) values ('2','COMERCIAL');
REM INSERTING into XE.T_HT_TIPO_TELEFONE
SET DEFINE OFF;
Insert into XE.T_HT_TIPO_TELEFONE (CD_TIPO_TELEFONE,NM_TIPO_TELEFONE) values ('1','CELULAR');
Insert into XE.T_HT_TIPO_TELEFONE (CD_TIPO_TELEFONE,NM_TIPO_TELEFONE) values ('2','RESIDÊNCIAL');
Insert into XE.T_HT_TIPO_TELEFONE (CD_TIPO_TELEFONE,NM_TIPO_TELEFONE) values ('3','COMERCIAL');
Insert into XE.T_HT_TIPO_TELEFONE (CD_TIPO_TELEFONE,NM_TIPO_TELEFONE) values ('4','RECADO');
REM INSERTING into XE.T_HT_USUARIO
SET DEFINE OFF;
Insert into XE.T_HT_USUARIO (CD_USUARIO,LOGIN,SENHA,NM_NOME,NM_SOBRENOME,SEXO,DT_NASCIMENTO,VL_ALTURA,DS_FOTO,DT_CADASTRO) values ('2','armandofc1','pass123','Armando','Costa','1',to_date('28/04/84','DD/MM/RR'),'1,72','foto.png',to_date('22/11/18','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index T_HT_ALIMENTACAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_ALIMENTACAO_PK" ON "XE"."T_HT_ALIMENTACAO" ("CD_ALIMENTACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_ATIVIDADE_FISICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_ATIVIDADE_FISICA_PK" ON "XE"."T_HT_ATIVIDADE_FISICA" ("CD_ATIVIDADE_FISICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_CONTATO_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_CONTATO_EMAIL_PK" ON "XE"."T_HT_CONTATO_EMAIL" ("CD_CONTATO", "CD_USUARIO", "CD_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_CONTATO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_CONTATO_PK" ON "XE"."T_HT_CONTATO" ("CD_CONTATO", "CD_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_CONTATO_TELEFONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_CONTATO_TELEFONE_PK" ON "XE"."T_HT_CONTATO_TELEFONE" ("CD_CONTATO", "CD_USUARIO", "CD_TELEFONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_EMAIL_PK" ON "XE"."T_HT_EMAIL" ("CD_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_ENDERECO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_ENDERECO_PK" ON "XE"."T_HT_ENDERECO" ("CD_ENDERECO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_ENDERECO_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_ENDERECO_USUARIO_PK" ON "XE"."T_HT_ENDERECO_USUARIO" ("CD_ENDERECO", "CD_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_ESTADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_ESTADO_PK" ON "XE"."T_HT_ESTADO" ("CD_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_EVOLUCAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_EVOLUCAO_PK" ON "XE"."T_HT_EVOLUCAO" ("CD_EVOLUCAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_MEDIDAS_CORPORAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_MEDIDAS_CORPORAIS_PK" ON "XE"."T_HT_MEDIDAS_CORPORAIS" ("CD_MEDIDAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_MENU_PK" ON "XE"."T_HT_MENU" ("CD_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_PAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_PAIS_PK" ON "XE"."T_HT_PAIS" ("CD_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_PESO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_PESO_PK" ON "XE"."T_HT_PESO" ("CD_PESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_PLANEJAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_PLANEJAMENTO_PK" ON "XE"."T_HT_PLANEJAMENTO" ("CD_PLANEJAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_PRESSAO_ARTERIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_PRESSAO_ARTERIAL_PK" ON "XE"."T_HT_PRESSAO_ARTERIAL" ("CD_PRESSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_TELEFONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_TELEFONE_PK" ON "XE"."T_HT_TELEFONE" ("CD_TELEFONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_TIPO_ALIMENTACAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_TIPO_ALIMENTACAO_PK" ON "XE"."T_HT_TIPO_ALIMENTACAO" ("CD_TIPO_ALIMENTACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_TIPO_ATIVIDADE_FISICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_TIPO_ATIVIDADE_FISICA_PK" ON "XE"."T_HT_TIPO_ATIVIDADE_FISICA" ("CD_TIPO_ATIVIDADE_FISICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_TIPO_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_TIPO_EMAIL_PK" ON "XE"."T_HT_TIPO_EMAIL" ("CD_TIPO_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_TIPO_ENDERECO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_TIPO_ENDERECO_PK" ON "XE"."T_HT_TIPO_ENDERECO" ("CD_TIPO_ENDERECO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_TIPO_TELEFONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_TIPO_TELEFONE_PK" ON "XE"."T_HT_TIPO_TELEFONE" ("CD_TIPO_TELEFONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_HT_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."T_HT_USUARIO_PK" ON "XE"."T_HT_USUARIO" ("CD_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger FKNTM_T_HT_ALIMENTACAO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "XE"."FKNTM_T_HT_ALIMENTACAO" BEFORE
    UPDATE OF cd_usuario ON t_ht_alimentacao
BEGIN
    raise_application_error(-20225,'Non Transferable FK constraint  on table T_HT_ALIMENTACAO is violated');
END;

/
ALTER TRIGGER "XE"."FKNTM_T_HT_ALIMENTACAO" ENABLE;
--------------------------------------------------------
--  Constraints for Table T_HT_ALIMENTACAO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ALIMENTACAO" ADD CONSTRAINT "T_HT_ALIMENTACAO_PK" PRIMARY KEY ("CD_ALIMENTACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_ALIMENTACAO" MODIFY ("CD_TIPO_ALIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ALIMENTACAO" MODIFY ("DT_CONSUMO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ALIMENTACAO" MODIFY ("VL_CALORIAS" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ALIMENTACAO" MODIFY ("NM_ALIMENTO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ALIMENTACAO" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ALIMENTACAO" MODIFY ("CD_ALIMENTACAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_ATIVIDADE_FISICA
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ATIVIDADE_FISICA" ADD CONSTRAINT "T_HT_ATIVIDADE_FISICA_PK" PRIMARY KEY ("CD_ATIVIDADE_FISICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_ATIVIDADE_FISICA" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ATIVIDADE_FISICA" MODIFY ("CD_TIPO_ATIVIDADE_FISICA" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ATIVIDADE_FISICA" MODIFY ("DT_REALIZADA" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ATIVIDADE_FISICA" MODIFY ("VL_GASTO_CALORICO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ATIVIDADE_FISICA" MODIFY ("NM_ATIVIDADE_FISICA" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ATIVIDADE_FISICA" MODIFY ("CD_ATIVIDADE_FISICA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_CONTATO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_CONTATO" ADD CONSTRAINT "T_HT_CONTATO_PK" PRIMARY KEY ("CD_CONTATO", "CD_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_CONTATO" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_CONTATO" MODIFY ("CD_CONTATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_CONTATO_EMAIL
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_CONTATO_EMAIL" ADD CONSTRAINT "T_HT_CONTATO_EMAIL_PK" PRIMARY KEY ("CD_CONTATO", "CD_USUARIO", "CD_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_CONTATO_EMAIL" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_CONTATO_EMAIL" MODIFY ("CD_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_CONTATO_EMAIL" MODIFY ("CD_CONTATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_CONTATO_TELEFONE
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_CONTATO_TELEFONE" ADD CONSTRAINT "T_HT_CONTATO_TELEFONE_PK" PRIMARY KEY ("CD_CONTATO", "CD_USUARIO", "CD_TELEFONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_CONTATO_TELEFONE" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_CONTATO_TELEFONE" MODIFY ("CD_TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_CONTATO_TELEFONE" MODIFY ("CD_CONTATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_EMAIL
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_EMAIL" ADD CONSTRAINT "T_HT_EMAIL_PK" PRIMARY KEY ("CD_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_EMAIL" MODIFY ("CD_TIPO_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_EMAIL" MODIFY ("DS_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_EMAIL" MODIFY ("CD_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_ENDERECO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ENDERECO" ADD CONSTRAINT "T_HT_ENDERECO_PK" PRIMARY KEY ("CD_ENDERECO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_ENDERECO" MODIFY ("VL_CEP" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ENDERECO" MODIFY ("VL_NUMERO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ENDERECO" MODIFY ("DS_RUA" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ENDERECO" MODIFY ("CD_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ENDERECO" MODIFY ("CD_TIPO_ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ENDERECO" MODIFY ("CD_ENDERECO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_ENDERECO_USUARIO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ENDERECO_USUARIO" ADD CONSTRAINT "T_HT_ENDERECO_USUARIO_PK" PRIMARY KEY ("CD_ENDERECO", "CD_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_ENDERECO_USUARIO" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ENDERECO_USUARIO" MODIFY ("CD_ENDERECO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_ESTADO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ESTADO" ADD CONSTRAINT "T_HT_ESTADO_PK" PRIMARY KEY ("CD_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_ESTADO" MODIFY ("NM_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ESTADO" MODIFY ("CD_PAIS" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_ESTADO" MODIFY ("CD_ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_EVOLUCAO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_EVOLUCAO" ADD CONSTRAINT "T_HT_EVOLUCAO_PK" PRIMARY KEY ("CD_EVOLUCAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_EVOLUCAO" MODIFY ("DT_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_EVOLUCAO" MODIFY ("CD_PRESSAO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_EVOLUCAO" MODIFY ("CD_MEDIDAS" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_EVOLUCAO" MODIFY ("CD_PESO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_EVOLUCAO" MODIFY ("CD_PLANEJAMENTO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_EVOLUCAO" MODIFY ("CD_EVOLUCAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_HISTORICO_ACESSO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_HISTORICO_ACESSO" MODIFY ("DT_ACESSO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_MEDIDAS_CORPORAIS
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_MEDIDAS_CORPORAIS" ADD CONSTRAINT "T_HT_MEDIDAS_CORPORAIS_PK" PRIMARY KEY ("CD_MEDIDAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_MEDIDAS_CORPORAIS" MODIFY ("DT_MEDICAO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_MEDIDAS_CORPORAIS" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_MEDIDAS_CORPORAIS" MODIFY ("CD_MEDIDAS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_MENU
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_MENU" ADD CONSTRAINT "T_HT_MENU_PK" PRIMARY KEY ("CD_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_MENU" MODIFY ("DS_CAMINHO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_MENU" MODIFY ("NM_MENU" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_MENU" MODIFY ("CD_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_PAIS
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_PAIS" ADD CONSTRAINT "T_HT_PAIS_PK" PRIMARY KEY ("CD_PAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_PAIS" MODIFY ("NM_PAIS" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PAIS" MODIFY ("CD_PAIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_PESO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_PESO" ADD CONSTRAINT "T_HT_PESO_PK" PRIMARY KEY ("CD_PESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_PESO" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PESO" MODIFY ("DT_MEDICAO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PESO" MODIFY ("VL_PESO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PESO" MODIFY ("CD_PESO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_PLANEJAMENTO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_PLANEJAMENTO" ADD CONSTRAINT "T_HT_PLANEJAMENTO_PK" PRIMARY KEY ("CD_PLANEJAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_PLANEJAMENTO" MODIFY ("DT_FIM" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PLANEJAMENTO" MODIFY ("DT_INICIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PLANEJAMENTO" MODIFY ("NM_PLANO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PLANEJAMENTO" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PLANEJAMENTO" MODIFY ("CD_PLANEJAMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_PRESSAO_ARTERIAL
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_PRESSAO_ARTERIAL" ADD CONSTRAINT "T_HT_PRESSAO_ARTERIAL_PK" PRIMARY KEY ("CD_PRESSAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_PRESSAO_ARTERIAL" MODIFY ("DT_MEDICAO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PRESSAO_ARTERIAL" MODIFY ("VL_PRESSAO_DIASTOLICA" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PRESSAO_ARTERIAL" MODIFY ("VL_PRESSAO_SISTOLICA" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PRESSAO_ARTERIAL" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_PRESSAO_ARTERIAL" MODIFY ("CD_PRESSAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_RELEMBRAR_SENHA
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_RELEMBRAR_SENHA" MODIFY ("DT_ENVIO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_RELEMBRAR_SENHA" MODIFY ("DM_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_TELEFONE
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_TELEFONE" ADD CONSTRAINT "T_HT_TELEFONE_PK" PRIMARY KEY ("CD_TELEFONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_TELEFONE" MODIFY ("VL_SUFIXO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_TELEFONE" MODIFY ("VL_PREFIXO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_TELEFONE" MODIFY ("VL_DDD" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_TELEFONE" MODIFY ("CD_TIPO_TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_TELEFONE" MODIFY ("CD_TELEFONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_TIPO_ALIMENTACAO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_TIPO_ALIMENTACAO" ADD CONSTRAINT "T_HT_TIPO_ALIMENTACAO_PK" PRIMARY KEY ("CD_TIPO_ALIMENTACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_TIPO_ALIMENTACAO" MODIFY ("NM_TIPO_ALIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_TIPO_ALIMENTACAO" MODIFY ("CD_TIPO_ALIMENTACAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_TIPO_ATIVIDADE_FISICA
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_TIPO_ATIVIDADE_FISICA" ADD CONSTRAINT "T_HT_TIPO_ATIVIDADE_FISICA_PK" PRIMARY KEY ("CD_TIPO_ATIVIDADE_FISICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_TIPO_ATIVIDADE_FISICA" MODIFY ("NM_TIPO_ATIVIDADE_FISICA" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_TIPO_ATIVIDADE_FISICA" MODIFY ("CD_TIPO_ATIVIDADE_FISICA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_TIPO_EMAIL
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_TIPO_EMAIL" ADD CONSTRAINT "T_HT_TIPO_EMAIL_PK" PRIMARY KEY ("CD_TIPO_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_TIPO_EMAIL" MODIFY ("NM_TIPO_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_TIPO_EMAIL" MODIFY ("CD_TIPO_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_TIPO_ENDERECO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_TIPO_ENDERECO" ADD CONSTRAINT "T_HT_TIPO_ENDERECO_PK" PRIMARY KEY ("CD_TIPO_ENDERECO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_TIPO_ENDERECO" MODIFY ("NM_TIPO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_TIPO_ENDERECO" MODIFY ("CD_TIPO_ENDERECO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_TIPO_TELEFONE
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_TIPO_TELEFONE" ADD CONSTRAINT "T_HT_TIPO_TELEFONE_PK" PRIMARY KEY ("CD_TIPO_TELEFONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_TIPO_TELEFONE" MODIFY ("NM_TIPO_TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_TIPO_TELEFONE" MODIFY ("CD_TIPO_TELEFONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_HT_USUARIO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_USUARIO" ADD CONSTRAINT "T_HT_USUARIO_PK" PRIMARY KEY ("CD_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "XE"."T_HT_USUARIO" MODIFY ("DT_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_USUARIO" MODIFY ("VL_ALTURA" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_USUARIO" MODIFY ("DT_NASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_USUARIO" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_USUARIO" MODIFY ("NM_NOME" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_USUARIO" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_USUARIO" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "XE"."T_HT_USUARIO" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_HT_ALIMENTACAO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ALIMENTACAO" ADD CONSTRAINT "RELATION_20" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
  ALTER TABLE "XE"."T_HT_ALIMENTACAO" ADD CONSTRAINT "RELATION_5" FOREIGN KEY ("CD_TIPO_ALIMENTACAO")
	  REFERENCES "XE"."T_HT_TIPO_ALIMENTACAO" ("CD_TIPO_ALIMENTACAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_ATIVIDADE_FISICA
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ATIVIDADE_FISICA" ADD CONSTRAINT "RELATION_22" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
  ALTER TABLE "XE"."T_HT_ATIVIDADE_FISICA" ADD CONSTRAINT "RELATION_4" FOREIGN KEY ("CD_TIPO_ATIVIDADE_FISICA")
	  REFERENCES "XE"."T_HT_TIPO_ATIVIDADE_FISICA" ("CD_TIPO_ATIVIDADE_FISICA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_CONTATO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_CONTATO" ADD CONSTRAINT "RELATION_17" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_CONTATO_EMAIL
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_CONTATO_EMAIL" ADD CONSTRAINT "RELATION_7" FOREIGN KEY ("CD_CONTATO", "CD_USUARIO")
	  REFERENCES "XE"."T_HT_CONTATO" ("CD_CONTATO", "CD_USUARIO") ENABLE;
  ALTER TABLE "XE"."T_HT_CONTATO_EMAIL" ADD CONSTRAINT "RELATION_8" FOREIGN KEY ("CD_EMAIL")
	  REFERENCES "XE"."T_HT_EMAIL" ("CD_EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_CONTATO_TELEFONE
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_CONTATO_TELEFONE" ADD CONSTRAINT "RELATION_10" FOREIGN KEY ("CD_TELEFONE")
	  REFERENCES "XE"."T_HT_TELEFONE" ("CD_TELEFONE") ENABLE;
  ALTER TABLE "XE"."T_HT_CONTATO_TELEFONE" ADD CONSTRAINT "RELATION_9" FOREIGN KEY ("CD_CONTATO", "CD_USUARIO")
	  REFERENCES "XE"."T_HT_CONTATO" ("CD_CONTATO", "CD_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_EMAIL
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_EMAIL" ADD CONSTRAINT "RELATION_1" FOREIGN KEY ("CD_TIPO_EMAIL")
	  REFERENCES "XE"."T_HT_TIPO_EMAIL" ("CD_TIPO_EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_ENDERECO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ENDERECO" ADD CONSTRAINT "RELATION_3" FOREIGN KEY ("CD_TIPO_ENDERECO")
	  REFERENCES "XE"."T_HT_TIPO_ENDERECO" ("CD_TIPO_ENDERECO") ENABLE;
  ALTER TABLE "XE"."T_HT_ENDERECO" ADD CONSTRAINT "RELATION_6" FOREIGN KEY ("CD_ESTADO")
	  REFERENCES "XE"."T_HT_ESTADO" ("CD_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_ENDERECO_USUARIO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ENDERECO_USUARIO" ADD CONSTRAINT "RELATION_11" FOREIGN KEY ("CD_ENDERECO")
	  REFERENCES "XE"."T_HT_ENDERECO" ("CD_ENDERECO") ENABLE;
  ALTER TABLE "XE"."T_HT_ENDERECO_USUARIO" ADD CONSTRAINT "RELATION_12" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_ESTADO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_ESTADO" ADD CONSTRAINT "RELATION_13" FOREIGN KEY ("CD_PAIS")
	  REFERENCES "XE"."T_HT_PAIS" ("CD_PAIS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_EVOLUCAO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_EVOLUCAO" ADD CONSTRAINT "RELATION_21" FOREIGN KEY ("CD_PLANEJAMENTO")
	  REFERENCES "XE"."T_HT_PLANEJAMENTO" ("CD_PLANEJAMENTO") ENABLE;
  ALTER TABLE "XE"."T_HT_EVOLUCAO" ADD CONSTRAINT "RELATION_27" FOREIGN KEY ("CD_PESO")
	  REFERENCES "XE"."T_HT_PESO" ("CD_PESO") ENABLE;
  ALTER TABLE "XE"."T_HT_EVOLUCAO" ADD CONSTRAINT "RELATION_28" FOREIGN KEY ("CD_PRESSAO")
	  REFERENCES "XE"."T_HT_PRESSAO_ARTERIAL" ("CD_PRESSAO") ENABLE;
  ALTER TABLE "XE"."T_HT_EVOLUCAO" ADD CONSTRAINT "RELATION_29" FOREIGN KEY ("CD_MEDIDAS")
	  REFERENCES "XE"."T_HT_MEDIDAS_CORPORAIS" ("CD_MEDIDAS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_HISTORICO_ACESSO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_HISTORICO_ACESSO" ADD CONSTRAINT "RELATION_16" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_MEDIDAS_CORPORAIS
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_MEDIDAS_CORPORAIS" ADD CONSTRAINT "RELATION_18" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_PESO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_PESO" ADD CONSTRAINT "RELATION_23" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_PLANEJAMENTO
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_PLANEJAMENTO" ADD CONSTRAINT "RELATION_30" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_PRESSAO_ARTERIAL
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_PRESSAO_ARTERIAL" ADD CONSTRAINT "RELATION_19" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_RELEMBRAR_SENHA
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_RELEMBRAR_SENHA" ADD CONSTRAINT "RELATION_31" FOREIGN KEY ("CD_USUARIO")
	  REFERENCES "XE"."T_HT_USUARIO" ("CD_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_HT_TELEFONE
--------------------------------------------------------

  ALTER TABLE "XE"."T_HT_TELEFONE" ADD CONSTRAINT "RELATION_2" FOREIGN KEY ("CD_TIPO_TELEFONE")
	  REFERENCES "XE"."T_HT_TIPO_TELEFONE" ("CD_TIPO_TELEFONE") ENABLE;
